WebUI/Controllers/OpenHourController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Dtos.OpenHourDto;

namespace WebUI.Controllers
{
    public class OpenHourController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public OpenHourController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:44346/api/OpenHour");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultOpenHourDtoUI>>(jsonData);
                return View(values);
            }


            return View();
        }

        [HttpGet]
        public IActionResult CreateOpenHour()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateOpenHour(CreateOpenHourDtoUI createOpenHourDtoUI)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createOpenHourDtoUI);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var responseMessage = await client.PostAsync("https://localhost:44346/api/OpenHour", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }


            return View(createOpenHourDtoUI);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteOpenHour(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:44346/api/OpenHour/{id}");


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateOpenHour(int id)
        {

            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:44346/api/OpenHour/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var json = await responseMessage.Content.ReadAsStringAsync();
                var OpenHour = JsonConvert.DeserializeObject<UpdateOpenHourDtoUI>(json);

                return View(OpenHour);

            }

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UpdateOpenHour(UpdateOpenHourDtoUI updateOpenHourDtoUI)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateOpenHourDtoUI);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var responseMessage = await client.PutAsync("https://localhost:44346/api/OpenHour/", stringContent);

            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

WebUI/Views/OpenHour/CreateOpenHour.cshtml
@model CreateOpenHourDtoUI

@{
    ViewData["Title"] = "CreateOpenHour";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}


<div class="row">
    <div class="col-md-12">

        <form method="post" asp-controller="OpenHour" asp-action="CreateOpenHour">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Rezervasyon Bilgisi Ekleme</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="OpenDays">Açık Günler</label>
                        <input type="text" class="form-control" asp-for="OpenDays" placeholder="Örneğin; Pazartesi - Cumertesi gibi">
                    </div>
                    <div class="form-group">
                        <label asp-for="OpeningHour">Açılma Saati</label>
                        <input type="text" class="form-control" asp-for="OpeningHour" placeholder="09.00 gibi">
                    </div>
                    <div class="form-group">
                        <label asp-for="ClosingHour">Kapanma Saati</label>
                        <input type="text" class="form-control" asp-for="ClosingHour" placeholder="19.30 gibi">
                    </div>


                    <div class="form-check">
                        <label>Durum</label><br>
                        <label class="form-radio-label">
                            <input class="form-radio-input" type="radio" asp-for="IsActive" value="true" checked="">
                            <span class="form-radio-sign">Aktif</span>
                        </label>
                        <label class="form-radio-label ml-3">
                            <input class="form-radio-input" type="radio" asp-for="IsActive" value="false">
                            <span class="form-radio-sign">Pasif</span>
                        </label>
                    </div>


                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Ekle</button>
                    <a class="btn btn-danger" asp-controller="OpenHour" asp-action="Index">Geri</a>
                </div>
            </div>
        </form>
    </div>

</div>

WebUI/Views/OpenHour/Index.cshtml
@model List<ResultOpenHourDtoUI>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/AdminLayout/Index.cshtml";
	int count = 1;
}


<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<div class="card-title">Açık Saatler Listesi</div>
			</div>
			<div class="card-body">
				<div class="card-sub">					
					<p class="fw-bold text-danger" text-danger">Tema bütünlüğü açısından Web sitesinde sadece bir çalışma saati gösterilebilir. </p>
					<p class="fw-bold text-danger">Bu listede aktif olarak seçilen çalışma saatlerinden ilki baz alınacaktır. </p>
				</div>
				<table class="table mt-3">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Açık Günler</th>
							<th scope="col">Açılma saati</th>
							<th scope="col">Kapanma saati</th>
							<th scope="col">Durum</th>
							
							<th scope="col">Sil</th>
							<th scope="col">Güncelle</th>
						</tr>
					</thead>
					<tbody>

						@foreach (var item in Model)
						{

							<tr>
								<td>@(count++)</td>
								<td>@item.OpenDays</td>
								<td>@item.OpeningHour</td>
								<td>@item.ClosingHour</td>

								<td>
									@if (item.IsActive)
									{
										<div class="badge badge-success">Aktif</div>
									}
									else
									{
										<div class="badge badge-danger">Pasif</div>
									}

								</td>

								<td>
									<a class=" btn btn-outline-danger sweetAlertConfirm" asp-controller="OpenHour" asp-action="DeleteOpenHour" asp-route-id="@item.Id">SİL</a>
								</td>
								<td>
									<a class=" btn btn-outline-warning" asp-controller="OpenHour" asp-action="UpdateOpenHour" asp-route-id="@item.Id">GÜNCELLE</a>
								</td>
							</tr>
						}


					</tbody>
				</table>

				<a class="btn btn-outline-success" asp-controller="OpenHour" asp-action="CreateOpenHour">Yeni Açık Saat Girişi</a>
			</div>
		</div>


	</div>

</div>

WebUI/Views/OpenHour/UpdateOpenHour.cshtml
@model UpdateOpenHourDtoUI

@{
    ViewData["Title"] = "UpdateOpenHour";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}


<div class="row">
    <div class="col-md-12">

        <form method="post" asp-controller="OpenHour" asp-action="UpdateOpenHour">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Açık Saatler Bilgisi Ekleme</div>
                </div>
                <div class="card-body">

                    <input type="hidden" asp-for="Id" />

                    <div class="form-group">
                        <label asp-for="OpenDays">Açık Günler</label>
                        <input type="text" class="form-control" asp-for="OpenDays">
                    </div>
                    <div class="form-group">
                        <label asp-for="OpeningHour">Açılma Saati</label>
                        <input type="text" class="form-control" asp-for="OpeningHour">
                    </div>
                    <div class="form-group">
                        <label asp-for="ClosingHour">Kapanma Saati</label>
                        <input type="text" class="form-control" asp-for="ClosingHour">
                    </div>

                    <div class="form-check">
                        <label>Durum</label><br>
                        <label class="form-radio-label">
                            <input class="form-radio-input" type="radio" asp-for="IsActive" value="true" checked="">
                            <span class="form-radio-sign">Aktif</span>
                        </label>
                        <label class="form-radio-label ml-3">
                            <input class="form-radio-input" type="radio" asp-for="IsActive" value="false">
                            <span class="form-radio-sign">Pasif</span>
                        </label>
                    </div>

                </div>
                <div class="card-action">
                    <button class="btn btn-success" type="submit">Güncelle</button>
                    <a class="btn btn-danger" asp-controller="OpenHour" asp-action="Index">Geri</a>
                </div>
            </div>
        </form>
    </div>

</div>